In [3]:
import sys
sys.path.append('/home/ec2-user/SEAJ-TEAM-4-')

In [5]:
import pandas as pd 
import matplotlib.pyplot as plt 

from backend.data_processing.constants import DEFAULT_TICKERS
from backend.data_analysis.loader import MarketDataLoader
from backend.data_analysis.cleaner import MarketDataCleaner
from backend.data_analysis.features import MarketFeatureEngineer

In [6]:
loader = MarketDataLoader()
raw_df = loader.load_analysis_data(DEFAULT_TICKERS)
raw_df.head()

2026-09-14 16:47:41,931 - INFO - Starting data load for 47 tickers
2026-09-14 16:47:41,933 - INFO - Downloading batch 1 with 47 tickers
2026-09-14 16:47:41,935 - INFO - Downloading historical data for 47 instruments from 2016-01-01 to None
2026-09-14 16:47:49,185 - INFO - Successfully downloaded data for batch of 47 tickers
2026-09-14 16:47:49,704 - INFO - Converted to long format: 126383 records, 7 columns
2026-09-14 16:47:49,706 - INFO - Successfully downloaded data for 126383 records across all batches
2026-09-14 16:50:03,153 - ERROR - Failed to load instrument metadata: connection to server at "10.9.69.224", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

2026-09-14 16:50:03,155 - WARNING - No metadata retrieved from PostgreSQL, returning market data only

  symbol       date       open       high        low      close     volume
0   AAPL 2016-01-04  23.072560  23.693165  22.935397  23.688667  270597600
1   AAPL 2016-01-05  23.778614  23.801099  23.027593  23.095049  223164000
2   AAPL 2016-01-06  22.611611  23.018604  22.456461  22.643091  273829600
3   AAPL 2016-01-07  22.188874  22.514916  21.682946  21.687443  324377600
4   AAPL 2016-01-08  22.159640  22.285559  21.757146  21.802116  283192000

In [9]:
raw_df.shape

(126383, 7)

In [10]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126383 entries, 0 to 126382
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  126383 non-null  object
 1   date    126383 non-null  datetime64[ns]
 2   open    126383 non-null  float64
 3   high    126383 non-null  float64
 4   low     126383 non-null  float64
 5   close   126383 non-null  float64
 6   volume  126383 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 6.7+ MB

In [11]:
raw_df.describe()

,date,open,high,low,close,volume
count,126383,126383.000000,126383.000000,126383.000000,126383.000000,1.263830e+05
mean,2021-05-06 16:44:37.575307008,176.366649,177.996120,174.690508,176.381746,2.874975e+07
min,2016-01-04 00:00:00,0.603037,0.622019,0.602307,0.613745,0.000000e+00
25%,2018-09-04 00:00:00,62.599659,62.962050,62.237031,62.590536,3.534000e+06
50%,2021-05-06 00:00:00,119.199937,120.280236,118.128074,119.287903,7.280000e+06
75%,2024-01-08 00:00:00,235.428254,237.879978,233.100997,235.477180,2.267270e+07
max,2026-09-14 00:00:00,1274.130005,1292.650024,1243.229980,1280.339966,3.692928e+09
std,NaN,167.414625,169.029778,165.719919,167.398676,7.878320e+07

In [12]:
raw_df["symbol"].nunique()

47

In [ ]:
# run if db connection working - not yet tested
#raw_df["asset_class"].value_counts()


raw_df.columns.tolist()
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126383 entries, 0 to 126382
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  126383 non-null  object
 1   date    126383 non-null  datetime64[ns]
 2   open    126383 non-null  float64
 3   high    126383 non-null  float64
 4   low     126383 non-null  float64
 5   close   126383 non-null  float64
 6   volume  126383 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 6.7+ MB

In [21]:
raw_df["date"].min()

Timestamp('2016-01-04 00:00:00')

In [22]:
raw_df["date"].max()

Timestamp('2026-09-14 00:00:00')